### ISSUE TITLE
building static libs fails during install

### ISSUE THREAD

**Issue by srtlg** [ampl/gsl#19]
building static libraries with VS2008 and VS2010 fails during installation since it tries to copy PDB files which do not exist.
The commit in question is 651b6af5fa89b4954e67ad2eae6c7bdd1d2ef77c
Going back to 8f07f98381db693f25d99e507dcb9b70c2026c00 (which I tagged v2.1-static) works for my application which expects static .lib files for linkage.

**Comment by fdabrandao** [comment]
Thanks for reporting this issue. The commit 651b6af5fa89b4954e67ad2eae6c7bdd1d2ef77c has been reverted in 48e0194da0d8921aff57c293b4f5083877d3f55b. Please let me know if the problem persists.

**Comment by srtlg** [comment]
I can probably test next Monday.  

Generally the idea of using the PDB files in dynamic debug builds might be useful to someone.  GSL is GPL licensed, however, such that I don't see the advantage in linking it dynamically under Windows.

**Comment by srtlg** [comment]
It works as expected.  Thanks 
If anybody wants the PDBs one could modify the commit 651b6af5fa89b4954e67ad2eae6c7bdd1d2ef77c
