### ISSUE TITLE
Call CMakeLists.txt from another CMake project

### ISSUE THREAD

**Issue by simonlegrand** [ampl/gsl#22]
Hello,

I am trying to call the CMakeLists.txt of the GSL from another project and I noticed the line 691:

`file(READ "${CMAKE_SOURCE_DIR}/gsl-config.in" GSL_CONFIG_FILE)`

The CMAKE_SOURCE_DIR is the directoy where the top-level CMakeLists.txt is located, which in my case means the directory of my project, where there is no gsl-config.in. I think it should be replaced by CMAKE_CURRENT_SOURCE_DIR which in any case is the directory where gsl-config.in is.

Best regards,

Simon

**Comment by fdabrandao** [comment]
Thanks for reporting this issue and for providing a solution. It has been fixed in 27e77fd970eccd8b299238fa94ed0563b9572ab9.
