### ISSUE TITLE
Wrong installation path for headers when CMAKE_INSTALL_PREFIX set

### ISSUE THREAD

**Issue by simonlegrand** [ampl/gsl#23]
Hello,

I'm working with windows 10 and Visual Studio 2017. I noticed that when the CMAKE_INSTALL_PREFIX is set, the headers are installed at the root of my machine. Removing the / before include/gsl at line 684 of the CMakeLists.txt solved the problem. The line then become:
`install(FILES ${GSL_HEADER_PATHS} DESTINATION include/gsl)`

Regards,

Simon

**Comment by fdabrandao** [comment]
Hi Simon,

In the master branch, line 684 of CMakeLists.txt is already `install(FILES ${GSL_HEADER_PATHS} DESTINATION include/gsl)`. Did you change anything else?

Best regards,
Filipe

**Comment by simonlegrand** [comment]
Ho I'm sorry I think I added this / myself and forgot to remove it... Next
time I'll compare with the master branch :D.

Best regards,

Simon

2017-06-14 2:32 GMT+02:00 Filipe Brandao <notifications@github.com>:
