### ISSUE TITLE
change path to gsl

### ISSUE THREAD

**Issue by hawkingsteven** [ampl/gsl#27]
Hello I would like to change the location of my gsl from
/home/gssctest/ScienceTools-v11r5p3-fssc-20180124/external/x86_64-unknown-linux-gnu-libc2.17

to 

/home/szakirov/Desktop/SRMP/ScienceTools-v11r5p3-fssc-20180124-x86_64-unknown-linux-gnu-libc2.17/x86_64-unknown-linux-gnu-libc2.17/include

How do I do this?

**Comment by hawkingsteven** [comment]
By the way I'm running scientific Linux 7

**Comment by fdabrandao** [comment]
This project provides CMake build support for the GSL library. Did you build and install gsl using this project or are you using the gsl version that came with your operating system?
