### ISSUE TITLE
[Installation Issue] Compile error in Ubuntu 18.04

### ISSUE THREAD

**Issue by authwork** [ampl/gsl#38]
Hello, I can successfully install gsl on Ubuntu 16.04.
But when I move to Ubuntu 18.04, -lm flag seems to be disappear and error happens like:
> gsl-2.5/siman/siman_tsp.c:83: undefined reference to `sincos'

note. This is not the error when using gsl, but compiling it.

**Comment by mapgccv** [comment]
I cannot reproduce the issue, it has been probably fixed in the previous releases.
