### ISSUE TITLE
sinc function not available

### ISSUE THREAD

**Issue by 4er4er4er** [ampl/gsl#42]
It appears that the GSL trigonometric functions have not been included. Many are built into AMPL anyway, but not all.

In particular one user needs sinc(x) = (if x != 0 then sin(x)/x else 1). This function can be implemented in AMPL using an if-then-else, but in the user's example that becomes awkward due to the large number of terms that use sinc and the complexity of the expressions that are arguments to sinc.

**Comment by mapgccv** [comment]
The definition I have found of `sinc` is not that one. In https://www.gnu.org/software/gsl/doc/html/specfunc.html#trigonometric-functions I found:
```
double gsl_sf_sinc(double x)
int gsl_sf_sinc_e(double x, gsl_sf_result * result)
These routines compute \sinc(x) = \sin(\pi x) / (\pi x) for any value of x.
```
