### ISSUE TITLE
(windows) not correctly detected by cmake 

### ISSUE THREAD

**Issue by F4L2** [ampl/gsl#45]
Hi,

For the purpose of compiling something with cmake.
I've installed the repository on windows via MinGW.  
With these commands precisely:

`./configure --prefix=C:/MinGW ` 
`make  `
`make install`

But when i'm trying to compile a project with cmake, it gives me this error:
`CMake Error at C:/Program Files/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find GSL (missing: GSL_LIBRARY GSL_CBLAS_LIBRARY) (found version
  "2.5")
`

Is there something i did wrong with the installation ?   
Because it does find the version but not the rest.  
I've also tried to install with cmake gui and visual studio, but with this method it wouldn't even find the version.

**Comment by mapgccv** [comment]
This is not related to this repository, which only provides support for building GSL via cmake.
You're building GSL using makefiles and importing it in a cmake project, see the section *reporting bugs* in the README file.
