### ISSUE TITLE
Give an option to statically link runtime

### ISSUE THREAD

**Issue by PawelTroka** [ampl/gsl#5]
It should be possible to generate Visual Studio projects that are building into dll but with statically linked VC++ runtime libraries, so that anyone can run this dll library without the need for vc_redist etc.

here is one approach:
http://stackoverflow.com/questions/10113017/setting-the-msvc-runtime-in-cmake

**Comment by vitaut** [comment]
Could you by any chance provide a PR?

**Comment by PawelTroka** [comment]
Sadly I don't have any experience with CMake. I can learn of course but it may take some time.

**Comment by vitaut** [comment]
Done in https://github.com/ampl/gsl/commit/be4c307b6d537f873e484373f9a4380584794195.
