### ISSUE TITLE
Clarify cmake build instructions

### ISSUE THREAD

**Issue by justin-hackin** [ampl/gsl#50]
It seems the purpose of this project is to provide a cmake for the project.  However, the INSTALL file does not give instructions on how to build with cmake.  Although this may seem obvious, it makes one uncertain of whether or not cmake will work and/or whether the old configure/make/make install will work in the project. Also, there's a deeply nested submodule that needs to get an init and update before one can start the build. Such documentation might expose the use of `NO_AMPL_BINDINGS` and explain what the impact of setting this flag is.  Do certain GSL features require the AMPL bindings or is this an extension of the GSL feature set?

**Comment by ceanwang** [comment]
I am trying to build it with GNU C (MINGW)+CMake under Windows 10. Here is my configure batch command, not fully working yet.
`MKDIR build_win10
CD build_win10
cmake -DCMAKE_MAKE_PROGRAM=make -DCMAKE_C_COMPILER=gcc -G "Unix Makefiles" ..`

**Comment by mapgccv** [comment]
I have added a section on the readme file called "About this repository"; I hope it clarifies things a bit. In short, this repository provides two things: AMPL bindings to GSL (a way to access GSL functions from the AMPL software) and cmake build support.

For a MinGW build, I'd reccomend:

```
md build
cd build
cmake -G"MinGW Makefiles" ..
cmake --build .
```
