### ISSUE TITLE
I only wish to build a subset of GSL's routines; how do I do this via CMake?

### ISSUE THREAD

**Issue by rdoddanavar** [ampl/gsl#52]
I have a project that only requires a handful of routines from GSL---for example, those in `gsl/ode-initval2`.

Is there a "clean" way (via some CMake options/variables?) to only build certain folders, and only include those in the final static lib `libgsl.a`?

Currently, my project's build time is dominated by GSL; it seems inefficient to build the entire library when I'm only using a small subset of it.

**Comment by mapgccv** [comment]
Hi, I have added an experimental support for that.

**Comment by rdoddanavar** [comment]
Alright, I'll go test this fix inside my project's build environment. I appreciate your help

**Comment by rdoddanavar** [comment]
Works great. Attached logs:
 - [cmake_log.txt](https://github.com/ampl/gsl/files/6402921/cmake_log.txt)
 - [make_log.txt](https://github.com/ampl/gsl/files/6402922/make_log.txt)

My environment:
- Ubuntu `20.04.2 LTS x86_64`
- CMake `3.10.2`
- gcc `9.3.0`

I'll leave it up to you to close this issue.

(lmk if y'all are open to donations)

**Comment by mapgccv** [comment]
Glad I could help!
