### ISSUE TITLE
gsl-hsitogramm manuel to be updated

### ISSUE THREAD

**Issue by lemiere** [ampl/gsl#53]
My gsl version is : 
```
gsl-config --version
2.5
```

In the gsl-randist manual, we can find : 
`gsl-randist 0 10000 cauchy 30 | gsl-histogram -- -100 100 200 > histogram.dat`

but in the gsl-histogramm, we have : 
` gsl-randist 0 10000 cauchy 30 | gsl-histogram -100 100 200 > histogram.dat`
Which is faulty as -100 is taken as an option...

easy fix, big help ! 
Yves

**Comment by mapgccv** [comment]
Thank you for the report: this repository contains only a copy of the upstream GSL repository, its original contribution being only the cmake build system. 
Making modifications to GSL here would not affect the upstream distribution and are hence not recommended.

As specified in the README file:

```
Reporting Bugs
==============

A list of known bugs can be found in the BUGS file.  Details of
compilation problems can be found in the INSTALL file.

If you find a bug which is not listed in these files please report it
to bug-gsl@gnu.org.
```
