### ISSUE TITLE
GSL Versioning

### ISSUE THREAD

**Issue by rdoddanavar** [ampl/gsl#59]
Hey guys;

Should we use e020de75f5b469b8cab600c9da64c39383ca9ab1 as GSL v2.6 and e11f1c774364c0411cc8785e2fdeeb52ab88f031 as GSL v2.7? 

Or should we wait for an official tag on the Releases page?

**Comment by fdabrandao** [comment]
Hi @rdoddanavar,

We have just created tags for these two versions (https://github.com/ampl/gsl/tags).
